### ISSUE TITLE
Update ModelPolisherOptions to allow for validation of unzipped output

### ISSUE THREAD

**Issue by mephenor** [draeger-lab/ModelPolisher#101] opened 2020-05-26 15:46 UTC
Removed the dependencies on Compression.ZIP or Compression.GZIP from SBML_Validation.
Guess this was done to save on bandwith when using online validation some time ago.
As offline validation is now the default, this restriction is no longer necessary.

**Comment by Schmoho** [comment] 2022-07-26 16:38
From the issue it is not apparent what was intended here and what the current state of affairs is.

There is a `ModelPolisher::validate` method which unzips in case the input File is zipped.
I don't see any necessity to do something about this at this point so I'm closing the ticket.

**Closed by Schmoho** 2022-07-26 16:38 UTC
